services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ewap-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ewap
      RABBITMQ_DEFAULT_PASS: ewap_dev_password
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: ewap-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ewap-api
    environment:
      NODE_ENV: production

      RABBITMQ_URL: amqp://ewap:ewap_dev_password@rabbitmq:5672
      RABBITMQ_QUEUE: ewap-workflows
      RABBITMQ_RETRY_QUEUE: ewap-workflows-retry
      RABBITMQ_DLQ: ewap-workflows-dlq

    ports:
      - "3002:3000"

    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started